import fs from "node:fs";
import path from "node:path";
import { z } from "zod";
import { Contract, Corrections, CpiU, Event, Organization, Person, Source } from "../src/schemas";

// JSON Schema is generated for editor validation of the YAML input (SPEC.md §4.8).
// Zod stays the single source of truth; never edit the generated files by hand.
const targets: Record<string, z.ZodType> = {
  event: Event,
  person: Person,
  organization: Organization,
  contract: Contract,
  source: Source,
  "cpi-u": CpiU,
  corrections: Corrections,
};

const outDir = path.resolve("schemas");
fs.mkdirSync(outDir, { recursive: true });
for (const [name, schema] of Object.entries(targets)) {
  const json = z.toJSONSchema(schema, { io: "input", unrepresentable: "any", target: "draft-2020-12" });
  const file = path.join(outDir, `${name}.schema.json`);
  fs.writeFileSync(file, JSON.stringify({ $comment: "GENERATED by npm run schema; do not edit.", ...json }, null, 2) + "\n");
  console.log(`wrote ${path.relative(process.cwd(), file)}`);
}
